## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# config by: Javier Zaleta Martínez (@jzaleta)

# Setups
right_format = """$cmd_duration$status"""
format = """
$username\
$hostname\
$time\
$directory\
$all\
$line_break\
$character"""

# Prompt symbols 
[character]
success_symbol = '[λ ](bold green)[->](bold green) [Shell](bold yellow) [\$](yellow)'
error_symbol = '[λ ](bold red)[->](bold red) [Shell](bold yellow) [\$](yellow)'

[username]
format = '[\[ $user\]]($style)'
style_user = 'cyan'
style_root = 'cyan'
show_always = true
disabled = false

[hostname]
format = ' in [\[󱄅 $hostname\]](bold red) '
trim_at = 'local.'
ssh_only = false
disabled = false

[directory]
format = '[ ](fg:yellow)[$path]($style) '
style = 'yellow'
truncation_symbol = './'
truncation_length = 4
read_only = ' '

[time]
format = '([\[ $time\] ]($style))'
style = 'yellow'
disabled = false

[cmd_duration]
format = '[󰮯 $duration]($style) '
style = 'yellow'
min_time = 1
disabled = false

[status]
format = '[$symbol$status]($style)'
symbol = '[󰊠 ](bold red)'
success_symbol = '[󰊠 ](bold green)'
style = 'red'
disabled = false

[line_break]
disabled = false

[jobs]
disabled = true

[fill]
symbol = ' '
style = 'grey'
