right_format = """$status"""

format = """
$username\
$hostname\
$time $cmd_duration\
$directory\
$all\
$line_break\
$character"""

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[username]
format = '[$user]($style)'
style_user = 'cyan'
style_root = 'cyan'
show_always = true
disabled = false

[hostname]
format = ' in [$hostname](bold red) '
trim_at = 'local.'
ssh_only = false
disabled = false

[directory]
truncation_symbol = './'
truncation_length = 4
read_only = ' '
style = 'yellow'

[status]
symbol = '[✗ ](bold red)'
success_symbol = '[✔ ](bold green)'
disabled = false

[time]
format = '\[[ $time]($style)\]'
style = 'yellow'
disabled = false

[line_break]
disabled = false

[jobs]
disabled = true

[fill]
# symbol = '•'
# style = 'grey'
