format = """
$username\
$hostname\
$directory\
$fill $cmd_duration $status\
$all\
$line_break\
$time \
$character"""

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[username]
format = '[$user]($style)'
show_always = true
disabled = false

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) in [$hostname](bold red) '
trim_at = 'local.'
disabled = false

[time]
format = '[$time]($style)'
style = 'bold white'
disabled = false

[status]
symbol = '[✖ ](bold red)'
success_symbol = '[✔ ](bold green)'
disabled = false

[fill]
symbol = '•'
style = 'grey'